### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [mozilla/mozdownload#609] opened 2020-07-29 14:07 UTC
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

```
find . -iname '*.py' | grep -Ev 'vendor|example|doc|tools|sphinx' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./setup.py:21: DeprecationWarning: invalid escape sequence \d
  return re.findall("__version__ = '([\d\.]+)'",
```

**Comment by whimboo** [comment] 2020-08-14 08:30
Thank you for the report. @tirkarthi, would you be also interested to get this issue fixed?

**Comment by tanmoydas9166** [comment] 2020-08-18 11:32
Can I fix this issue?

**Comment by tirkarthi** [comment] 2020-08-18 11:38
@tanmoydas9166 Feel free to pick it up.

**Comment by tanmoydas9166** [comment] 2020-08-18 15:13
Sir, please check my PR.

**Comment by whimboo** [comment] 2020-08-27 11:52
@tanmoydas9166 thanks for picking up this issue. I had a look at open PRs but sadly I cannot find the one from you. Did you actually create one? It's not enough to only push the changes to your own fork.

**Comment by paridhi7** [comment] 2020-09-01 07:41
Hi, I'm new to open source. Is this issue still open?

**Comment by whimboo** [comment] 2020-09-08 09:02
I haven't seen a PR being opened by @tanmoydas9166 yet. So feel free to pick-up this issue. Thanks.

**Comment by sahilsandhu** [comment] 2020-09-09 18:50
Hi, i am new to open source, is this issue resolved or it is still opened??

**Comment by whimboo** [comment] 2020-09-09 20:08
It's currently being worked on via PR #610. But maybe you want to help with https://github.com/mozilla/mozdownload/issues/247.

**Comment by rishishounak** [comment] 2020-09-12 17:19
If the issue is still open could I join in

**Comment by whimboo** [comment] 2020-09-14 06:36
If we don't hear back from @tanmoydas9166 within two days feel free to provide your own PR. Thanks!

**Comment by rishishounak** [comment] 2020-09-14 14:11
I need some guidance to get started as I am new

**Comment by whimboo** [comment] 2020-09-16 07:30
@rishishounak please check https://github.com/mozilla/mozdownload/pull/610 for the changes and my review comments. Those will be the lines of code you will have to change. Once done submit a PR. Thanks.

**Comment by rishishounak** [comment] 2020-09-16 16:16
Please whether what I have done is correct

**Comment by rishishounak** [comment] 2020-09-16 16:17
Please check whether I have made the right changes

**Comment by tanmaysinghal98** [comment] 2020-09-21 19:05
@whimboo I am a first timer, can I pick this up?

**Comment by rishishounak** [comment] 2020-09-21 19:12
@whimboo please check my pr

**Comment by whimboo** [comment] 2020-12-27 13:58
Fixed by #612.

**Closed by whimboo** 2020-12-27 13:58 UTC
Labels: mentored, python
