### ISSUE TITLE
Large regression in tinderbox download times

### ISSUE THREAD

**Issue by EricRahm** [mozilla/mozdownload#253] opened 2015-02-12 01:21 UTC
It looks like c73e81463c11cd9667d58322390fa99b6a35b135 caused a very large regression in the amount of time it takes to lookup a tinderbox build. The `is_build_dir` check needs to be moved, the simple solution would be to move it to *after* we filter by timestamp / date.

**Comment by whimboo** [comment] 2015-02-12 17:17
Thanks Eric! So it is a regression from issue #143. If that regression is important for you to get fixed we could do it quickly and get a follow-up release out.

**Comment by EricRahm** [comment] 2015-02-12 17:20
@whimboo yes, it's causing several minute delays per build.

**Comment by whimboo** [comment] 2015-02-16 13:29
Definitely something we want to have for the 1.14 release.

**Comment by whimboo** [comment] 2015-02-26 14:24
PR #254 has been merged! Thank you @EricRahm for fixing it!

**Comment by whimboo** [comment] 2015-02-27 12:49
It looks like we may have a problem with index==0. We have to check that.

**Comment by whimboo** [comment] 2015-03-04 10:41
I checked this myself and it's only an issue of what we actually print out as failure message for the URL. It's not critical and if necessary can be fixed in another issue. For details see: https://github.com/mozilla/mozdownload/pull/254/files#r25765397. Closing out this issue.

**Closed by whimboo** 2015-03-04 10:41 UTC
Labels: must-have
